### PR TITLE
React Project Structure Proposal

### PR DESCRIPTION
**Pull request by Abdallah-Youssef**
We should all follow the same structure when creating our components. This is my suggested structure:

- Each page should be in its own folder in the components folder.
- Shared components would be in the root of the components folder, i.e. not belonging to any page's folder.
- Files that contain the API request handlers would be in the API folder.
- Images/Icons would be in the assets folder.
- Any custom hooks would be in the hooks folder.

Extra: Using [CSS modules](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/) will allow us to have locally scoped CSS classes to avoid conflicts.

### CODE REVIEW

**Comment by Abdallah-Youssef** [comment]
@TalaatHarb Could we add Eng Omar to help us in reviewing PRs?

**Comment by TalaatHarb** [comment]
I will add everyone who puts his mail as a replay to the message I posted on the zoom channel,

I assume that Page1 and Page2 will later be renamed to something descriptive, like user-edit-screen and such? you are just doing it this way to make sure that the router you added works?

**Comment by Abdallah-Youssef** [comment]
Yes, this is just a template for others to use. I also show how to use the CSS modules.

**Comment by Abdallah-Youssef** [comment]
I want to close this pr because I realized it doesn't make any sense. I will discuss with everyone what structure we should use and just use it.

**Comment by Abdallah-Youssef** [comment]
We will document whatever structure we agree on.

**Review by Mah0mar — CHANGES_REQUESTED** [review]
Looks good,
but you can put each component files(.js, .css, .test) directly in components folder.

Shared Components should follow the same approach we follow with normal components and  I prefer to put parent components ( components that contains your business and don't have much styles ) out of components folder.

You must not use ( Component ) in naming your components.

**Review by Mah0mar — COMMENTED** [review]
try to add prettier extension for vscode it will fix spacing issues and make your code looks better. 

Why do you use (. module) in naming css files?

**Comment by Abdallah-Youssef** [comment]
so that the styling of a component is local and doesn't affect other components that could have similar CSS class names

**Review by TalaatHarb — APPROVED** [review]

**Pull request merged**
